on:
  push:
    branches: [ main ]

jobs:
  run:
    name: Build project and testbench
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build toolchain
        run: |
             sudo apt update
             sudo apt install -y make gcc git zip
             git clone https://github.com/cc65/cc65
             cd cc65
             make all
             tar -cvf cc65.tar.gz asminc bin cfg include lib samples target
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG="$(date +%y%m%d)"
          curl -sL -XPOST -d '{"tag_name": "'$RELEASE_TAG'"}' \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H 'Content-Type: application/json' \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
          RELEASE_ID=$(curl -svL https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/$RELEASE_TAG | jq .id)
          cd cc65
          RELEASE_FILE="cc65.tar.gz"
          curl -sL -XPOST -T ${RELEASE_FILE}* \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type:application/octet-stream" \
            "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/$RELEASE_ID/assets?&name=cc65-$RELEASE_TAG.tar.gz"
        shell: bash
